apiVersion: v1
kind: Service

metadata:
  name: wordpress-service
  labels:
    app: web-wordpress
    version: v1

spec:
  type: NodePort
  selector:
    microservice: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
